apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "chart.fullname" . }}"
  podManagementPolicy: "Parallel" # This setting means that the StatefulSet controller doesn't block applying changes until the existing Pod is READY.
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }} # Automatically Roll Deployments
      {{- with .Values.podSpec.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext: {{ toYaml .Values.podSpec.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.podSpec.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and (semverCompare ">= 0.4.7" (include "chromadb.apiVersion" .)) .Values.chromadb.auth.enabled (eq .Values.chromadb.auth.type "basic") }}
      initContainers:
        - name: generate-htpasswd
          image: {{ .Values.initImage }}
          env:
            - name: CHROMA_BASIC_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.chromadb.auth.existingSecret | default "chromadb-auth" }}
                  key: username
            - name: CHROMA_BASIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.chromadb.auth.existingSecret | default "chromadb-auth" }}
                  key: password
          command:
            - sh
            - -c
            - |
              htpasswd -Bbn ${CHROMA_BASIC_USER} ${CHROMA_BASIC_PASSWORD} > /chroma/auth/server.htpasswd
              chmod 444 /chroma/auth/server.htpasswd
          volumeMounts:
            - mountPath: /chroma/auth/
              name: htpasswd-volume
      {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: "chromadb"
          image: "{{ .Values.image.repository }}:{{ .Values.chromadb.apiVersion | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          {{- if and (semverCompare "< 1.0.0" (include "chromadb.apiVersion" .)) .Values.chromadb.auth.enabled }}
          envFrom:
            - configMapRef:
                {{- if (eq .Values.chromadb.auth.type "token") }}
                name: {{ include "chart.fullname" . }}-token-auth-config
                {{- end }}
                {{- if (eq .Values.chromadb.auth.type "basic") }}
                name: {{ include "chart.fullname" . }}-basic-auth-config
                {{- end }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if and (semverCompare "< 1.0.0" (include "chromadb.apiVersion" .)) }}
            - name: IS_PERSISTENT
              value: "{{ .Values.chromadb.isPersistent }}"
            - name: PERSIST_DIRECTORY
              value: "{{ .Values.chromadb.persistDirectory }}"
            - name: ALLOW_RESET
              value: "{{ .Values.chromadb.allowReset | default false}}"
            - name: ANONYMIZED_TELEMETRY
              value: "{{ .Values.chromadb.anonymizedTelemetry | default false }}"
            {{- if .Values.chromadb.corsAllowOrigins }}
            - name: CHROMA_SERVER_CORS_ALLOW_ORIGINS
              value: '{{ .Values.chromadb.corsAllowOrigins | join "\",\"" | printf "[\"%s\"]"}}'
            {{- end }}
            - name: ROOT_LOG_LEVEL
              value: "{{ .Values.chromadb.logging.root | upper | default "WARN" }}"
            - name: CHROMA_LOG_LEVEL
              value: "{{ .Values.chromadb.logging.chromadb | upper | default "DEBUG" }}"
            - name: UVICORN_LOG_LEVEL_UVICORN
              value: "{{ .Values.chromadb.logging.uvicorn | upper | default "INFO" }}"
            {{- if .Values.chromadb.maintenance.collection_cache_policy }}
            {{- if ne .Values.chromadb.maintenance.collection_cache_policy "LRU" }}
                {{- fail "collection_cache_policy must be 'LRU'" }}
            {{- end }}
            - name: CHROMA_SEGMENT_CACHE_POLICY
              value: "{{ .Values.chromadb.maintenance.collection_cache_policy }}"
            - name: CHROMA_MEMORY_LIMIT_BYTES
              {{- $bytes := int .Values.chromadb.maintenance.collection_cache_limit_bytes }}
              {{- if le $bytes 0 }}
                {{- fail "collection_cache_limit_bytes must be a positive integer" }}
              {{- end }}
              value: "{{ $bytes }}"
            {{- end }}
            {{- end }}
            {{- if .Values.chromadb.serverHttpPort }}
            - name: CHROMA_SERVER_HTTP_PORT
              value: "{{ .Values.chromadb.serverHttpPort }}"
            {{- end }}
            # We keep this for backwards compatibility log levels below are used for the new images
            {{- if and (semverCompare "< 1.0.0" (include "chromadb.apiVersion" .)) .Values.chromadb.logConfigFileLocation }}
            - name: CHROMA_LOG_CONFIG
            {{- if .Values.chromadb.logConfigMap }}
              value: "/chroma/log_config.yaml"
            {{- else }}
              value: "{{ .Values.chromadb.logConfigFileLocation }}"
            {{- end }}
            {{- end }}
            {{- if and (semverCompare "< 1.0.0" (include "chromadb.apiVersion" .)) .Values.chromadb.auth.enabled (eq .Values.chromadb.auth.type "token") }}
            {{- if and (semverCompare ">= 0.4.7" (include "chromadb.apiVersion" .)) (semverCompare "< 0.5.0" (include "chromadb.apiVersion" .)) }}
            - name: CHROMA_SERVER_AUTH_CREDENTIALS
            {{- else if (semverCompare ">= 0.5.0" (include "chromadb.apiVersion" .))}}
            - name: CHROMA_SERVER_AUTHN_CREDENTIALS
            {{- end }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.chromadb.auth.existingSecret | default "chromadb-auth" }}
                  key: token
            {{- end }}
          ports:
            - containerPort: {{ .Values.chromadb.serverHttpPort }}
              name: http
          {{- if or .Values.resources.requests .Values.resources.limits}}
          resources:
            {{- if .Values.resources.requests }}
            requests: {{ .Values.resources.requests | toYaml | nindent 14 }}
            {{- end }}
            {{- if .Values.resources.limits }}
            limits: {{ .Values.resources.limits | toYaml | nindent 14 }}
            {{- end }}
          {{- end }}
          securityContext: {{ .Values.podSpec.securityContext | toYaml  | nindent 14 }}
          volumeMounts:
            {{- if and (semverCompare "< 1.0.0" (include "chromadb.apiVersion" .)) (semverCompare ">= 0.6.0" (include "chromadb.apiVersion" .)) }}
            - mountPath: "/chroma/log_config.yaml"
              name: log-config
              subPath: log_config.yaml
            {{- else if (semverCompare "< 0.5.0" (include "chromadb.apiVersion" .))}}
            - mountPath: "/chroma/log_config.yaml"
              name: log-config-legacy
              subPath: log_config.yaml
            {{- end }}
            {{- if eq .Values.chromadb.isPersistent true }}
            - mountPath: "{{.Values.chromadb.persistDirectory}}"
              name: data
            {{- end }}
            {{- if and (semverCompare "< 1.0.0" (include "chromadb.apiVersion" .)) (semverCompare ">= 0.4.7" (include "chromadb.apiVersion" .)) .Values.chromadb.auth.enabled (eq .Values.chromadb.auth.type "basic") }}
            - mountPath: /chroma/auth/
              name: htpasswd-volume
            {{- end }}
            {{- if (semverCompare ">= 1.0.0" (include "chromadb.apiVersion" .)) }}
            - mountPath: /config.yaml
              name: v1-config
              subPath: config.yaml
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.chromadb.serverHttpPort }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.chromadb.serverHttpPort }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.chromadb.serverHttpPort }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
      volumes:
        {{- if and (semverCompare "< 1.0.0" (include "chromadb.apiVersion" .)) (semverCompare ">= 0.4.7" (include "chromadb.apiVersion" .)) .Values.chromadb.auth.enabled (eq .Values.chromadb.auth.type "basic") }}
        - name: htpasswd-volume
          emptyDir: { }
        {{- end }}
        {{- if (semverCompare "< 0.5.0" (include "chromadb.apiVersion" .)) }}
        - name: log-config-legacy
          configMap:
            name: "log-config"
            defaultMode: 0644
        {{- end }}
        {{- if .Values.chromadb.logConfigMap }}
        - name: log-config
          configMap:
            name: "{{ .Values.chromadb.logConfigMap }}"
            defaultMode: 0644
        {{- else }}
        - name: log-config
          configMap:
            name:  "log-config"
            defaultMode: 0644
        {{- end }}
        {{- if (semverCompare ">= 1.0.0" (include "chromadb.apiVersion" .)) }}
        - name: v1-config
          configMap:
            name: v1-config
            defaultMode: 0644
        {{- end }}
  {{- if eq .Values.chromadb.isPersistent true }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: {{ .Values.chromadb.data.accessModes | toYaml | nindent 14 }}
        {{- if .Values.chromadb.data.storageClass }}
        storageClassName: "{{ .Values.chromadb.data.storageClass }}"
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.chromadb.data.volumeSize }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted:  {{ .Values.chromadb.data.retentionPolicyOnDelete | default "Delete" }}
  {{- end }}
